### ISSUE TITLE
Process is not defined when used with vite react app

### ISSUE THREAD

**Issue by coldspice** [contentful/rich-text#713]
Uncaught ReferenceError: process is not defined
    at node_modules/@contentful/rich-text-from-markdown/dist/rich-text-from-markdown.es5.js (@contentful_rich-text-from-markdown.js:17300:19)
    at __require (chunk-BUSYA2B4.js:3:50)
    at @contentful_rich-text-from-markdown.js:18137:16

i'm getting this error when i tried it on freshly created react app with vite

**Comment by coldspice** [comment]
i tried tracing it, it is originating from vfile library which is exporting module.export = process

can anyone suggest any workaround for this

**Comment by chrishelgert** [comment]
we are now providing also an esm export, does it work better with vite now?
